name: Deploy firebase functions
on:
  push:
    branches:
      - main
    paths:
      - "firebase-functions/**"
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master

      - name: Install Dependencies
        run: npm ci
        working-directory: firebase-functions

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Install Dependencies
        run: npm ci
        working-directory: firebase-functions/functions
        
      # see https://github.com/google-github-actions/auth for details
      - name: Authenticate to Google Cloud
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }}'

      - name: Deploy to Firebase
        env:
          GMAIL_USER: ${{ secrets.GMAIL_USER }}
          GMAIL_PASS: ${{ secrets.GMAIL_PASS }}
          DATACITE_AUTH_HASH: ${{ secrets.DATACITE_AUTH_HASH }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_ACCESSKEYID: ${{ secrets.AWS_ACCESSKEYID }}
          AWS_SECRETACCESSKEY: ${{ secrets.AWS_SECRETACCESSKEY }}
          GITHUB_AUTH: ${{ secrets.ISSUE_CREATOR_PAT }}
          REACT_APP_GOOGLE_CLOUD_API_KEY: ${{ secrets.REACT_APP_GOOGLE_CLOUD_API_KEY }}
          REACT_APP_GOOGLE_CLOUD_API_KEY_DEV: ${{ secrets.REACT_APP_GOOGLE_CLOUD_API_KEY_DEV }}
          PROJECT_PATH: ./firebase-functions
        run: |
          echo "Creating .env file..."
          echo "GMAIL_USER=${{ secrets.GMAIL_USER }}" >> .env
          echo "GMAIL_PASS=${{ secrets.GMAIL_PASS }}" >> .env
          echo "DATACITE_AUTH_HASH=${{ secrets.DATACITE_AUTH_HASH }}" >> .env
          echo "AWS_REGION=${{ secrets.AWS_REGION }}" >> .env
          echo "AWS_ACCESSKEYID=${{ secrets.AWS_ACCESSKEYID }}" >> .env
          echo "AWS_SECRETACCESSKEY=${{ secrets.AWS_SECRETACCESSKEY }}" >> .env
          echo "GITHUB_AUTH=${{ secrets.ISSUE_CREATOR_PAT }}" >> .env
          echo "REACT_APP_GOOGLE_CLOUD_API_KEY=${{ secrets.REACT_APP_GOOGLE_CLOUD_API_KEY }}" >> .env
          echo "REACT_APP_GOOGLE_CLOUD_API_KEY_DEV=${{ secrets.REACT_APP_GOOGLE_CLOUD_API_KEY_DEV }}" >> .env
          echo "Deploying to Firebase..."
          firebase deploy --only functions --project cioos-metadata-form --non-interactive --debug
        working-directory: firebase-functions/functions

